export const NOTE_DETAILS_32_KEYS = [
  {
    note: "C2",
    key: "Z",
    frequency: 65.406,
    type: "natural",
    octave: 2,
    position: 1,
  },
  {
    note: "Db2",
    key: "S",
    frequency: 69.296,
    type: "accidental",
    octave: 2,
    position: 2,
  },
  {
    note: "D2",
    key: "X",
    frequency: 73.416,
    type: "natural",
    octave: 2,
    position: 3,
  },
  {
    note: "Eb2",
    key: "D",
    frequency: 77.782,
    type: "accidental",
    octave: 2,
    position: 4,
  },
  {
    note: "E2",
    key: "C",
    frequency: 82.407,
    type: "natural",
    octave: 2,
    position: 5,
  },
  {
    note: "F2",
    key: "V",
    frequency: 87.307,
    type: "natural",
    octave: 2,
    position: 6,
  },
  {
    note: "Gb2",
    key: "G",
    frequency: 92.499,
    type: "accidental",
    octave: 2,
    position: 7,
  },
  {
    note: "G2",
    key: "B",
    frequency: 97.999,
    type: "natural",
    octave: 2,
    position: 8,
  },
  {
    note: "Ab2",
    key: "H",
    frequency: 103.826,
    type: "accidental",
    octave: 2,
    position: 9,
  },
  {
    note: "A2",
    key: "N",
    frequency: 110.0,
    type: "natural",
    octave: 2,
    position: 10,
  },
  {
    note: "Bb2",
    key: "J",
    frequency: 116.541,
    type: "accidental",
    octave: 2,
    position: 11,
  },
  {
    note: "B2",
    key: "M",
    frequency: 123.471,
    type: "natural",
    octave: 2,
    position: 12,
  },
  {
    note: "C3",
    key: "Q",
    frequency: 130.813,
    type: "natural",
    octave: 3,
    position: 13,
  },
  {
    note: "Db3",
    key: "2",
    frequency: 138.591,
    type: "accidental",
    octave: 3,
    position: 14,
  },
  {
    note: "D3",
    key: "W",
    frequency: 146.832,
    type: "natural",
    octave: 3,
    position: 15,
  },
  {
    note: "Eb3",
    key: "3",
    frequency: 155.563,
    type: "accidental",
    octave: 3,
    position: 16,
  },
  {
    note: "E3",
    key: "E",
    frequency: 164.814,
    type: "natural",
    octave: 3,
    position: 17,
  },
  {
    note: "F3",
    key: "R",
    frequency: 174.614,
    type: "natural",
    octave: 3,
    position: 18,
  },
  {
    note: "Gb3",
    key: "5",
    frequency: 184.997,
    type: "accidental",
    octave: 3,
    position: 19,
  },
  {
    note: "G3",
    key: "T",
    frequency: 195.998,
    type: "natural",
    octave: 3,
    position: 20,
  },
  {
    note: "Ab3",
    key: "6",
    frequency: 207.652,
    type: "accidental",
    octave: 3,
    position: 21,
  },
  {
    note: "A3",
    key: "Y",
    frequency: 220.0,
    type: "natural",
    octave: 3,
    position: 22,
  },
  {
    note: "Bb3",
    key: "7",
    frequency: 233.082,
    type: "accidental",
    octave: 3,
    position: 23,
  },
  {
    note: "B3",
    key: "U",
    frequency: 246.942,
    type: "natural",
    octave: 3,
    position: 24,
  },
  {
    note: "C4",
    key: "I",
    frequency: 261.626,
    type: "natural",
    octave: 4,
    position: 25,
  },
  {
    note: "Db4",
    key: "9",
    frequency: 277.183,
    type: "accidental",
    octave: 4,
    position: 26,
  },
  {
    note: "D4",
    key: "O",
    frequency: 293.665,
    type: "natural",
    octave: 4,
    position: 27,
  },
  {
    note: "Eb4",
    key: "0",
    frequency: 311.127,
    type: "accidental",
    octave: 4,
    position: 28,
  },
  {
    note: "E4",
    key: "P",
    frequency: 329.628,
    type: "natural",
    octave: 4,
    position: 29,
  },
  {
    note: "F4",
    key: "[",
    frequency: 349.228,
    type: "natural",
    octave: 4,
    position: 30,
  },
  {
    note: "Gb4",
    key: "=",
    frequency: 369.994,
    type: "accidental",
    octave: 4,
    position: 31,
  },
  {
    note: "G4",
    key: "]",
    frequency: 391.995,
    type: "natural",
    octave: 4,
    position: 32,
  },
];

//49 keys piano
export const NOTE_DETAILS_49_KEYS = [
  {
    note: "C2",
    key: "Z",
    frequency: 65.406,
    type: "natural",
    octave: 2,
    position: 1,
  },
  {
    note: "Db2",
    key: "S",
    frequency: 69.296,
    type: "accidental",
    octave: 2,
    position: 2,
  },
  {
    note: "D2",
    key: "X",
    frequency: 73.416,
    type: "natural",
    octave: 2,
    position: 3,
  },
  {
    note: "Eb2",
    key: "D",
    frequency: 77.782,
    type: "accidental",
    octave: 2,
    position: 4,
  },
  {
    note: "E2",
    key: "C",
    frequency: 82.407,
    type: "natural",
    octave: 2,
    position: 5,
  },
  {
    note: "F2",
    key: "V",
    frequency: 87.307,
    type: "natural",
    octave: 2,
    position: 6,
  },
  {
    note: "Gb2",
    key: "G",
    frequency: 92.499,
    type: "accidental",
    octave: 2,
    position: 7,
  },
  {
    note: "G2",
    key: "B",
    frequency: 97.999,
    type: "natural",
    octave: 2,
    position: 8,
  },
  {
    note: "Ab2",
    key: "H",
    frequency: 103.826,
    type: "accidental",
    octave: 2,
    position: 9,
  },
  {
    note: "A2",
    key: "N",
    frequency: 110.0,
    type: "natural",
    octave: 2,
    position: 10,
  },
  {
    note: "Bb2",
    key: "J",
    frequency: 116.541,
    type: "accidental",
    octave: 2,
    position: 11,
  },
  {
    note: "B2",
    key: "M",
    frequency: 123.471,
    type: "natural",
    octave: 2,
    position: 12,
  },
  {
    note: "C3",
    key: "Q",
    frequency: 130.813,
    type: "natural",
    octave: 3,
    position: 13,
  },
  {
    note: "Db3",
    key: "2",
    frequency: 138.591,
    type: "accidental",
    octave: 3,
    position: 14,
  },
  {
    note: "D3",
    key: "W",
    frequency: 146.832,
    type: "natural",
    octave: 3,
    position: 15,
  },
  {
    note: "Eb3",
    key: "3",
    frequency: 155.563,
    type: "accidental",
    octave: 3,
    position: 16,
  },
  {
    note: "E3",
    key: "E",
    frequency: 164.814,
    type: "natural",
    octave: 3,
    position: 17,
  },
  {
    note: "F3",
    key: "R",
    frequency: 174.614,
    type: "natural",
    octave: 3,
    position: 18,
  },
  {
    note: "Gb3",
    key: "5",
    frequency: 184.997,
    type: "accidental",
    octave: 3,
    position: 19,
  },
  {
    note: "G3",
    key: "T",
    frequency: 195.998,
    type: "natural",
    octave: 3,
    position: 20,
  },
  {
    note: "Ab3",
    key: "6",
    frequency: 207.652,
    type: "accidental",
    octave: 3,
    position: 21,
  },
  {
    note: "A3",
    key: "Y",
    frequency: 220.0,
    type: "natural",
    octave: 3,
    position: 22,
  },
  {
    note: "Bb3",
    key: "7",
    frequency: 233.082,
    type: "accidental",
    octave: 3,
    position: 23,
  },
  {
    note: "B3",
    key: "U",
    frequency: 246.942,
    type: "natural",
    octave: 3,
    position: 24,
  },
  {
    note: "C4",
    key: "I",
    frequency: 261.626,
    type: "natural",
    octave: 4,
    position: 25,
  },
  {
    note: "Db4",
    key: "9",
    frequency: 277.183,
    type: "accidental",
    octave: 4,
    position: 26,
  },
  {
    note: "D4",
    key: "O",
    frequency: 293.665,
    type: "natural",
    octave: 4,
    position: 27,
  },
  {
    note: "Eb4",
    key: "0",
    frequency: 311.127,
    type: "accidental",
    octave: 4,
    position: 28,
  },
  {
    note: "E4",
    key: "P",
    frequency: 329.628,
    type: "natural",
    octave: 4,
    position: 29,
  },
  {
    note: "F4",
    key: "[",
    frequency: 349.228,
    type: "natural",
    octave: 4,
    position: 30,
  },
  {
    note: "Gb4",
    key: "=",
    frequency: 369.994,
    type: "accidental",
    octave: 4,
    position: 31,
  },
  {
    note: "G4",
    key: "]",
    frequency: 391.995,
    type: "natural",
    octave: 4,
    position: 32,
  },
  {
    note: "Ab4",
    key: "\\",
    frequency: 415.305,
    type: "accidental",
    octave: 4,
    position: 33,
  },
  {
    note: "A4",
    key: ";",
    frequency: 440.0,
    type: "natural",
    octave: 4,
    position: 34,
  },
  {
    note: "Bb4",
    key: "'",
    frequency: 466.164,
    type: "accidental",
    octave: 4,
    position: 35,
  },
  {
    note: "B4",
    key: "/",
    frequency: 493.883,
    type: "natural",
    octave: 4,
    position: 36,
  },
  {
    note: "C5",
    key: ".",
    frequency: 523.251,
    type: "natural",
    octave: 5,
    position: 37,
  },
  {
    note: "Db5",
    key: ",",
    frequency: 554.365,
    type: "accidental",
    octave: 5,
    position: 38,
  },
  {
    note: "D5",
    key: "L",
    frequency: 587.33,
    type: "natural",
    octave: 5,
    position: 39,
  },
  {
    note: "Eb5",
    key: "K",
    frequency: 622.254,
    type: "accidental",
    octave: 5,
    position: 40,
  },
  {
    note: "E5",
    key: "J",
    frequency: 659.255,
    type: "natural",
    octave: 5,
    position: 41,
  },
  {
    note: "F5",
    key: "H",
    frequency: 698.456,
    type: "natural",
    octave: 5,
    position: 42,
  },
  {
    note: "Gb5",
    key: "G",
    frequency: 739.989,
    type: "accidental",
    octave: 5,
    position: 43,
  },
  {
    note: "G5",
    key: "F",
    frequency: 783.991,
    type: "natural",
    octave: 5,
    position: 44,
  },
  {
    note: "Ab5",
    key: "D",
    frequency: 830.609,
    type: "accidental",
    octave: 5,
    position: 45,
  },
  {
    note: "A5",
    key: "S",
    frequency: 880.0,
    type: "natural",
    octave: 5,
    position: 46,
  },
  {
    note: "Bb5",
    key: "A",
    frequency: 932.328,
    type: "accidental",
    octave: 5,
    position: 47,
  },
  {
    note: "B5",
    key: "Z",
    frequency: 987.767,
    type: "natural",
    octave: 5,
    position: 48,
  },
  {
    note: "C6",
    key: "X",
    frequency: 1046.502,
    type: "natural",
    octave: 6,
    position: 49,
  },
];

//61 keys piano
export const NOTE_DETAILS_61_KEYS = [
  {
    note: "C2",
    key: "Z",
    frequency: 65.406,
    type: "natural",
    octave: 2,
    position: 1,
  },
  {
    note: "Db2",
    key: "S",
    frequency: 69.296,
    type: "accidental",
    octave: 2,
    position: 2,
  },
  {
    note: "D2",
    key: "X",
    frequency: 73.416,
    type: "natural",
    octave: 2,
    position: 3,
  },
  {
    note: "Eb2",
    key: "D",
    frequency: 77.782,
    type: "accidental",
    octave: 2,
    position: 4,
  },
  {
    note: "E2",
    key: "C",
    frequency: 82.407,
    type: "natural",
    octave: 2,
    position: 5,
  },
  {
    note: "F2",
    key: "V",
    frequency: 87.307,
    type: "natural",
    octave: 2,
    position: 6,
  },
  {
    note: "Gb2",
    key: "G",
    frequency: 92.499,
    type: "accidental",
    octave: 2,
    position: 7,
  },
  {
    note: "G2",
    key: "B",
    frequency: 97.999,
    type: "natural",
    octave: 2,
    position: 8,
  },
  {
    note: "Ab2",
    key: "H",
    frequency: 103.826,
    type: "accidental",
    octave: 2,
    position: 9,
  },
  {
    note: "A2",
    key: "N",
    frequency: 110.0,
    type: "natural",
    octave: 2,
    position: 10,
  },
  {
    note: "Bb2",
    key: "J",
    frequency: 116.541,
    type: "accidental",
    octave: 2,
    position: 11,
  },
  {
    note: "B2",
    key: "M",
    frequency: 123.471,
    type: "natural",
    octave: 2,
    position: 12,
  },
  {
    note: "C3",
    key: "Q",
    frequency: 130.813,
    type: "natural",
    octave: 3,
    position: 13,
  },
  {
    note: "Db3",
    key: "2",
    frequency: 138.591,
    type: "accidental",
    octave: 3,
    position: 14,
  },
  {
    note: "D3",
    key: "W",
    frequency: 146.832,
    type: "natural",
    octave: 3,
    position: 15,
  },
  {
    note: "Eb3",
    key: "3",
    frequency: 155.563,
    type: "accidental",
    octave: 3,
    position: 16,
  },
  {
    note: "E3",
    key: "E",
    frequency: 164.814,
    type: "natural",
    octave: 3,
    position: 17,
  },
  {
    note: "F3",
    key: "R",
    frequency: 174.614,
    type: "natural",
    octave: 3,
    position: 18,
  },
  {
    note: "Gb3",
    key: "5",
    frequency: 184.997,
    type: "accidental",
    octave: 3,
    position: 19,
  },
  {
    note: "G3",
    key: "T",
    frequency: 195.998,
    type: "natural",
    octave: 3,
    position: 20,
  },
  {
    note: "Ab3",
    key: "6",
    frequency: 207.652,
    type: "accidental",
    octave: 3,
    position: 21,
  },
  {
    note: "A3",
    key: "Y",
    frequency: 220.0,
    type: "natural",
    octave: 3,
    position: 22,
  },
  {
    note: "Bb3",
    key: "7",
    frequency: 233.082,
    type: "accidental",
    octave: 3,
    position: 23,
  },
  {
    note: "B3",
    key: "U",
    frequency: 246.942,
    type: "natural",
    octave: 3,
    position: 24,
  },
  {
    note: "C4",
    key: "I",
    frequency: 261.626,
    type: "natural",
    octave: 4,
    position: 25,
  },
  {
    note: "Db4",
    key: "9",
    frequency: 277.183,
    type: "accidental",
    octave: 4,
    position: 26,
  },
  {
    note: "D4",
    key: "O",
    frequency: 293.665,
    type: "natural",
    octave: 4,
    position: 27,
  },
  {
    note: "Eb4",
    key: "0",
    frequency: 311.127,
    type: "accidental",
    octave: 4,
    position: 28,
  },
  {
    note: "E4",
    key: "P",
    frequency: 329.628,
    type: "natural",
    octave: 4,
    position: 29,
  },
  {
    note: "F4",
    key: "[",
    frequency: 349.228,
    type: "natural",
    octave: 4,
    position: 30,
  },
  {
    note: "Gb4",
    key: "=",
    frequency: 369.994,
    type: "accidental",
    octave: 4,
    position: 31,
  },
  {
    note: "G4",
    key: "]",
    frequency: 391.995,
    type: "natural",
    octave: 4,
    position: 32,
  },
  {
    note: "Ab4",
    key: "\\",
    frequency: 415.305,
    type: "accidental",
    octave: 4,
    position: 33,
  },
  {
    note: "A4",
    key: ";",
    frequency: 440.0,
    type: "natural",
    octave: 4,
    position: 34,
  },
  {
    note: "Bb4",
    key: "'",
    frequency: 466.164,
    type: "accidental",
    octave: 4,
    position: 35,
  },
  {
    note: "B4",
    key: "/",
    frequency: 493.883,
    type: "natural",
    octave: 4,
    position: 36,
  },
  {
    note: "C5",
    key: ".",
    frequency: 523.251,
    type: "natural",
    octave: 5,
    position: 37,
  },
  {
    note: "Db5",
    key: ",",
    frequency: 554.365,
    type: "accidental",
    octave: 5,
    position: 38,
  },
  {
    note: "D5",
    key: "L",
    frequency: 587.33,
    type: "natural",
    octave: 5,
    position: 39,
  },
  {
    note: "Eb5",
    key: "K",
    frequency: 622.254,
    type: "accidental",
    octave: 5,
    position: 40,
  },
  {
    note: "E5",
    key: "J",
    frequency: 659.255,
    type: "natural",
    octave: 5,
    position: 41,
  },
  {
    note: "F5",
    key: "H",
    frequency: 698.456,
    type: "natural",
    octave: 5,
    position: 42,
  },
  {
    note: "Gb5",
    key: "G",
    frequency: 739.989,
    type: "accidental",
    octave: 5,
    position: 43,
  },
  {
    note: "G5",
    key: "F",
    frequency: 783.991,
    type: "natural",
    octave: 5,
    position: 44,
  },
  {
    note: "Ab5",
    key: "D",
    frequency: 830.609,
    type: "accidental",
    octave: 5,
    position: 45,
  },
  {
    note: "A5",
    key: "S",
    frequency: 880.0,
    type: "natural",
    octave: 5,
    position: 46,
  },
  {
    note: "Bb5",
    key: "A",
    frequency: 932.328,
    type: "accidental",
    octave: 5,
    position: 47,
  },
  {
    note: "B5",
    key: "Z",
    frequency: 987.767,
    type: "natural",
    octave: 5,
    position: 48,
  },
  {
    note: "C6",
    key: "X",
    frequency: 1046.502,
    type: "natural",
    octave: 6,
    position: 49,
  },
  {
    note: "Db6",
    key: "C",
    frequency: 1108.731,
    type: "accidental",
    octave: 6,
    position: 50,
  },
  {
    note: "D6",
    key: "V",
    frequency: 1174.659,
    type: "natural",
    octave: 6,
    position: 51,
  },
  {
    note: "Eb6",
    key: "B",
    frequency: 1244.508,
    type: "accidental",
    octave: 6,
    position: 52,
  },
  {
    note: "E6",
    key: "N",
    frequency: 1318.51,
    type: "natural",
    octave: 6,
    position: 53,
  },
  {
    note: "F6",
    key: "M",
    frequency: 1396.913,
    type: "natural",
    octave: 6,
    position: 54,
  },
  {
    note: "Gb6",
    key: ",",
    frequency: 1479.978,
    type: "accidental",
    octave: 6,
    position: 55,
  },
  {
    note: "G6",
    key: ".",
    frequency: 1567.982,
    type: "natural",
    octave: 6,
    position: 56,
  },
  {
    note: "Ab6",
    key: "/",
    frequency: 1661.219,
    type: "accidental",
    octave: 6,
    position: 57,
  },
  {
    note: "A6",
    key: "L",
    frequency: 1760.0,
    type: "natural",
    octave: 6,
    position: 58,
  },
  {
    note: "Bb6",
    key: "P",
    frequency: 1864.655,
    type: "accidental",
    octave: 6,
    position: 59,
  },
  {
    note: "B6",
    key: "Q",
    frequency: 1975.533,
    type: "natural",
    octave: 6,
    position: 60,
  },
  {
    note: "C7",
    key: "O",
    frequency: 2093.005,
    type: "natural",
    octave: 7,
    position: 61,
  },
];

//76 keys piano
export const NOTE_DETAILS_76_KEYS = [
  {
    note: "E1",
    key: "Z",
    frequency: 41.203,
    type: "natural",
    octave: 1,
    position: 1,
  },
  {
    note: "F1",
    key: "X",
    frequency: 43.654,
    type: "natural",
    octave: 1,
    position: 2,
  },
  {
    note: "Gb1",
    key: "S",
    frequency: 46.249,
    type: "accidental",
    octave: 1,
    position: 3,
  },
  {
    note: "G1",
    key: "C",
    frequency: 48.999,
    type: "natural",
    octave: 1,
    position: 4,
  },
  {
    note: "Ab1",
    key: "D",
    frequency: 51.913,
    type: "accidental",
    octave: 1,
    position: 5,
  },
  {
    note: "A1",
    key: "V",
    frequency: 55.0,
    type: "natural",
    octave: 1,
    position: 6,
  },
  {
    note: "Bb1",
    key: "G",
    frequency: 58.27,
    type: "accidental",
    octave: 1,
    position: 7,
  },
  {
    note: "B1",
    key: "B",
    frequency: 61.735,
    type: "natural",
    octave: 1,
    position: 8,
  },
  {
    note: "C2",
    key: "N",
    frequency: 65.406,
    type: "natural",
    octave: 2,
    position: 9,
  },
  {
    note: "Db2",
    key: "H",
    frequency: 69.296,
    type: "accidental",
    octave: 2,
    position: 10,
  },
  {
    note: "D2",
    key: "M",
    frequency: 73.416,
    type: "natural",
    octave: 2,
    position: 11,
  },
  {
    note: "Eb2",
    key: "J",
    frequency: 77.782,
    type: "accidental",
    octave: 2,
    position: 12,
  },
  {
    note: "E2",
    key: ",",
    frequency: 82.407,
    type: "natural",
    octave: 2,
    position: 13,
  },
  {
    note: "F2",
    key: ".",
    frequency: 87.307,
    type: "natural",
    octave: 2,
    position: 14,
  },
  {
    note: "Gb2",
    key: "/",
    frequency: 92.499,
    type: "accidental",
    octave: 2,
    position: 15,
  },
  {
    note: "G2",
    key: "Q",
    frequency: 97.999,
    type: "natural",
    octave: 2,
    position: 16,
  },
  {
    note: "Ab2",
    key: "2",
    frequency: 103.826,
    type: "accidental",
    octave: 2,
    position: 17,
  },
  {
    note: "A2",
    key: "W",
    frequency: 110.0,
    type: "natural",
    octave: 2,
    position: 18,
  },
  {
    note: "Bb2",
    key: "3",
    frequency: 116.541,
    type: "accidental",
    octave: 2,
    position: 19,
  },
  {
    note: "B2",
    key: "E",
    frequency: 123.471,
    type: "natural",
    octave: 2,
    position: 20,
  },
  {
    note: "C3",
    key: "R",
    frequency: 130.813,
    type: "natural",
    octave: 3,
    position: 21,
  },
  {
    note: "Db3",
    key: "5",
    frequency: 138.591,
    type: "accidental",
    octave: 3,
    position: 22,
  },
  {
    note: "D3",
    key: "T",
    frequency: 146.832,
    type: "natural",
    octave: 3,
    position: 23,
  },
  {
    note: "Eb3",
    key: "6",
    frequency: 155.563,
    type: "accidental",
    octave: 3,
    position: 24,
  },
  {
    note: "E3",
    key: "Y",
    frequency: 164.814,
    type: "natural",
    octave: 3,
    position: 25,
  },
  {
    note: "F3",
    key: "7",
    frequency: 174.614,
    type: "natural",
    octave: 3,
    position: 26,
  },
  {
    note: "Gb3",
    key: "U",
    frequency: 184.997,
    type: "accidental",
    octave: 3,
    position: 27,
  },
  {
    note: "G3",
    key: "I",
    frequency: 195.998,
    type: "natural",
    octave: 3,
    position: 28,
  },
  {
    note: "Ab3",
    key: "9",
    frequency: 207.652,
    type: "accidental",
    octave: 3,
    position: 29,
  },
  {
    note: "A3",
    key: "O",
    frequency: 220.0,
    type: "natural",
    octave: 3,
    position: 30,
  },
  {
    note: "Bb3",
    key: "0",
    frequency: 233.082,
    type: "accidental",
    octave: 3,
    position: 31,
  },
  {
    note: "B3",
    key: "P",
    frequency: 246.942,
    type: "natural",
    octave: 3,
    position: 32,
  },
  {
    note: "C4",
    key: "[",
    frequency: 261.626,
    type: "natural",
    octave: 4,
    position: 33,
  },
  {
    note: "Db4",
    key: "=",
    frequency: 277.183,
    type: "accidental",
    octave: 4,
    position: 34,
  },
  {
    note: "D4",
    key: "]",
    frequency: 293.665,
    type: "natural",
    octave: 4,
    position: 35,
  },
  {
    note: "Eb4",
    key: "\\",
    frequency: 311.127,
    type: "accidental",
    octave: 4,
    position: 36,
  },
  {
    note: "E4",
    key: "L",
    frequency: 329.628,
    type: "natural",
    octave: 4,
    position: 37,
  },
  {
    note: "F4",
    key: ";",
    frequency: 349.228,
    type: "natural",
    octave: 4,
    position: 38,
  },
  {
    note: "Gb4",
    key: "'",
    frequency: 369.994,
    type: "accidental",
    octave: 4,
    position: 39,
  },
  {
    note: "G4",
    key: "/",
    frequency: 391.995,
    type: "natural",
    octave: 4,
    position: 40,
  },
  {
    note: "Ab4",
    key: "A",
    frequency: 415.305,
    type: "accidental",
    octave: 4,
    position: 41,
  },
  {
    note: "A4",
    key: "S",
    frequency: 440.0,
    type: "natural",
    octave: 4,
    position: 42,
  },
  {
    note: "Bb4",
    key: "D",
    frequency: 466.164,
    type: "accidental",
    octave: 4,
    position: 43,
  },
  {
    note: "B4",
    key: "F",
    frequency: 493.883,
    type: "natural",
    octave: 4,
    position: 44,
  },
  {
    note: "C5",
    key: "G",
    frequency: 523.251,
    type: "natural",
    octave: 5,
    position: 45,
  },
  {
    note: "Db5",
    key: "H",
    frequency: 554.365,
    type: "accidental",
    octave: 5,
    position: 46,
  },
  {
    note: "D5",
    key: "J",
    frequency: 587.33,
    type: "natural",
    octave: 5,
    position: 47,
  },
  {
    note: "Eb5",
    key: "K",
    frequency: 622.254,
    type: "accidental",
    octave: 5,
    position: 48,
  },
  {
    note: "E5",
    key: "L",
    frequency: 659.255,
    type: "natural",
    octave: 5,
    position: 49,
  },
  {
    note: "F5",
    key: ";",
    frequency: 698.456,
    type: "natural",
    octave: 5,
    position: 50,
  },
  {
    note: "Gb5",
    key: "'",
    frequency: 739.989,
    type: "accidental",
    octave: 5,
    position: 51,
  },
  {
    note: "G5",
    key: "Z",
    frequency: 783.991,
    type: "natural",
    octave: 5,
    position: 52,
  },
  {
    note: "Ab5",
    key: "X",
    frequency: 830.609,
    type: "accidental",
    octave: 5,
    position: 53,
  },
  {
    note: "A5",
    key: "C",
    frequency: 880.0,
    type: "natural",
    octave: 5,
    position: 54,
  },
  {
    note: "Bb5",
    key: "V",
    frequency: 932.328,
    type: "accidental",
    octave: 5,
    position: 55,
  },
  {
    note: "B5",
    key: "B",
    frequency: 987.767,
    type: "natural",
    octave: 5,
    position: 56,
  },
  {
    note: "C6",
    key: "N",
    frequency: 1046.502,
    type: "natural",
    octave: 6,
    position: 57,
  },
  {
    note: "Db6",
    key: "M",
    frequency: 1108.731,
    type: "accidental",
    octave: 6,
    position: 58,
  },
  {
    note: "D6",
    key: ",",
    frequency: 1174.659,
    type: "natural",
    octave: 6,
    position: 59,
  },
  {
    note: "Eb6",
    key: ".",
    frequency: 1244.508,
    type: "accidental",
    octave: 6,
    position: 60,
  },
  {
    note: "E6",
    key: "/",
    frequency: 1318.51,
    type: "natural",
    octave: 6,
    position: 61,
  },
  {
    note: "F6",
    key: "Q",
    frequency: 1396.913,
    type: "natural",
    octave: 6,
    position: 62,
  },
  {
    note: "Gb6",
    key: "W",
    frequency: 1479.978,
    type: "accidental",
    octave: 6,
    position: 63,
  },
  {
    note: "G6",
    key: "E",
    frequency: 1567.982,
    type: "natural",
    octave: 6,
    position: 64,
  },
  {
    note: "Ab6",
    key: "T",
    frequency: 1661.219,
    type: "accidental",
    octave: 6,
    position: 65,
  },
  {
    note: "A6",
    key: "Y",
    frequency: 1760.0,
    type: "natural",
    octave: 6,
    position: 66,
  },
  {
    note: "Bb6",
    key: "U",
    frequency: 1864.655,
    type: "accidental",
    octave: 6,
    position: 67,
  },
  {
    note: "B6",
    key: "I",
    frequency: 1975.533,
    type: "natural",
    octave: 6,
    position: 68,
  },
  {
    note: "C7",
    key: "O",
    frequency: 2093.005,
    type: "natural",
    octave: 7,
    position: 69,
  },
  {
    note: "Db7",
    key: "P",
    frequency: 2217.461,
    type: "accidental",
    octave: 7,
    position: 70,
  },
  {
    note: "D7",
    key: "[",
    frequency: 2349.318,
    type: "natural",
    octave: 7,
    position: 71,
  },
  {
    note: "Eb7",
    key: "]",
    frequency: 2489.016,
    type: "accidental",
    octave: 7,
    position: 72,
  },
  {
    note: "E7",
    key: "\\",
    frequency: 2637.02,
    type: "natural",
    octave: 7,
    position: 73,
  },
  {
    note: "F7",
    key: "A",
    frequency: 2793.826,
    type: "natural",
    octave: 7,
    position: 74,
  },
  {
    note: "Gb7",
    key: "S",
    frequency: 2959.955,
    type: "accidental",
    octave: 7,
    position: 75,
  },
  {
    note: "G7",
    key: "D",
    frequency: 3135.964,
    type: "natural",
    octave: 7,
    position: 76,
  },
];

//88 keys piano
export const NOTE_DETAILS_88_KEYS = [
  {
    note: "A0",
    key: "Z",
    frequency: 27.5,
    type: "natural",
    octave: 0,
    position: 1,
  },
  {
    note: "Bb0",
    key: "S",
    frequency: 29.135,
    type: "accidental",
    octave: 0,
    position: 2,
  },
  {
    note: "B0",
    key: "X",
    frequency: 30.868,
    type: "natural",
    octave: 0,
    position: 3,
  },
  {
    note: "C1",
    key: "C",
    frequency: 32.703,
    type: "natural",
    octave: 1,
    position: 4,
  },
  {
    note: "Db1",
    key: "D",
    frequency: 34.648,
    type: "accidental",
    octave: 1,
    position: 5,
  },
  {
    note: "D1",
    key: "V",
    frequency: 36.708,
    type: "natural",
    octave: 1,
    position: 6,
  },
  {
    note: "Eb1",
    key: "G",
    frequency: 38.891,
    type: "accidental",
    octave: 1,
    position: 7,
  },
  {
    note: "E1",
    key: "B",
    frequency: 41.203,
    type: "natural",
    octave: 1,
    position: 8,
  },
  {
    note: "F1",
    key: "N",
    frequency: 43.654,
    type: "natural",
    octave: 1,
    position: 9,
  },
  {
    note: "Gb1",
    key: "H",
    frequency: 46.249,
    type: "accidental",
    octave: 1,
    position: 10,
  },
  {
    note: "G1",
    key: "M",
    frequency: 48.999,
    type: "natural",
    octave: 1,
    position: 11,
  },
  {
    note: "Ab1",
    key: "J",
    frequency: 51.913,
    type: "accidental",
    octave: 1,
    position: 12,
  },
  {
    note: "A1",
    key: ",",
    frequency: 55.0,
    type: "natural",
    octave: 1,
    position: 13,
  },
  {
    note: "Bb1",
    key: "K",
    frequency: 58.27,
    type: "accidental",
    octave: 1,
    position: 14,
  },
  {
    note: "B1",
    key: ".",
    frequency: 61.735,
    type: "natural",
    octave: 1,
    position: 15,
  },
  {
    note: "C2",
    key: "/",
    frequency: 65.406,
    type: "natural",
    octave: 2,
    position: 16,
  },
  {
    note: "Db2",
    key: "Q",
    frequency: 69.296,
    type: "accidental",
    octave: 2,
    position: 17,
  },
  {
    note: "D2",
    key: "W",
    frequency: 73.416,
    type: "natural",
    octave: 2,
    position: 18,
  },
  {
    note: "Eb2",
    key: "E",
    frequency: 77.782,
    type: "accidental",
    octave: 2,
    position: 19,
  },
  {
    note: "E2",
    key: "R",
    frequency: 82.407,
    type: "natural",
    octave: 2,
    position: 20,
  },
  {
    note: "F2",
    key: "T",
    frequency: 87.307,
    type: "natural",
    octave: 2,
    position: 21,
  },
  {
    note: "Gb2",
    key: "Y",
    frequency: 92.499,
    type: "accidental",
    octave: 2,
    position: 22,
  },
  {
    note: "G2",
    key: "U",
    frequency: 97.999,
    type: "natural",
    octave: 2,
    position: 23,
  },
  {
    note: "Ab2",
    key: "I",
    frequency: 103.826,
    type: "accidental",
    octave: 2,
    position: 24,
  },
  {
    note: "A2",
    key: "O",
    frequency: 110.0,
    type: "natural",
    octave: 2,
    position: 25,
  },
  {
    note: "Bb2",
    key: "P",
    frequency: 116.541,
    type: "accidental",
    octave: 2,
    position: 26,
  },
  {
    note: "B2",
    key: "[",
    frequency: 123.471,
    type: "natural",
    octave: 2,
    position: 27,
  },
  {
    note: "C3",
    key: "]",
    frequency: 130.813,
    type: "natural",
    octave: 3,
    position: 28,
  },
  {
    note: "Db3",
    key: "\\",
    frequency: 138.591,
    type: "accidental",
    octave: 3,
    position: 29,
  },
  {
    note: "D3",
    key: "A",
    frequency: 146.832,
    type: "natural",
    octave: 3,
    position: 30,
  },
  {
    note: "Eb3",
    key: "S",
    frequency: 155.563,
    type: "accidental",
    octave: 3,
    position: 31,
  },
  {
    note: "E3",
    key: "D",
    frequency: 164.814,
    type: "natural",
    octave: 3,
    position: 32,
  },
  {
    note: "F3",
    key: "F",
    frequency: 174.614,
    type: "natural",
    octave: 3,
    position: 33,
  },
  {
    note: "Gb3",
    key: "G",
    frequency: 184.997,
    type: "accidental",
    octave: 3,
    position: 34,
  },
  {
    note: "G3",
    key: "H",
    frequency: 195.998,
    type: "natural",
    octave: 3,
    position: 35,
  },
  {
    note: "Ab3",
    key: "J",
    frequency: 207.652,
    type: "accidental",
    octave: 3,
    position: 36,
  },
  {
    note: "A3",
    key: "K",
    frequency: 220.0,
    type: "natural",
    octave: 3,
    position: 37,
  },
  {
    note: "Bb3",
    key: "L",
    frequency: 233.082,
    type: "accidental",
    octave: 3,
    position: 38,
  },
  {
    note: "B3",
    key: ";",
    frequency: 246.942,
    type: "natural",
    octave: 3,
    position: 39,
  },
  {
    note: "C4",
    key: "'",
    frequency: 261.626,
    type: "natural",
    octave: 4,
    position: 40,
  },
  {
    note: "Db4",
    key: "Z",
    frequency: 277.183,
    type: "accidental",
    octave: 4,
    position: 41,
  },
  {
    note: "D4",
    key: "X",
    frequency: 293.665,
    type: "natural",
    octave: 4,
    position: 42,
  },
  {
    note: "Eb4",
    key: "C",
    frequency: 311.127,
    type: "accidental",
    octave: 4,
    position: 43,
  },
  {
    note: "E4",
    key: "V",
    frequency: 329.628,
    type: "natural",
    octave: 4,
    position: 44,
  },
  {
    note: "F4",
    key: "B",
    frequency: 349.228,
    type: "natural",
    octave: 4,
    position: 45,
  },
  {
    note: "Gb4",
    key: "N",
    frequency: 369.994,
    type: "accidental",
    octave: 4,
    position: 46,
  },
  {
    note: "G4",
    key: "M",
    frequency: 391.995,
    type: "natural",
    octave: 4,
    position: 47,
  },
  {
    note: "Ab4",
    key: ",",
    frequency: 415.305,
    type: "accidental",
    octave: 4,
    position: 48,
  },
  {
    note: "A4",
    key: ".",
    frequency: 440.0,
    type: "natural",
    octave: 4,
    position: 49,
  },
  {
    note: "Bb4",
    key: "/",
    frequency: 466.164,
    type: "accidental",
    octave: 4,
    position: 50,
  },
  {
    note: "B4",
    key: "Q",
    frequency: 493.883,
    type: "natural",
    octave: 4,
    position: 51,
  },
  {
    note: "C5",
    key: "W",
    frequency: 523.251,
    type: "natural",
    octave: 5,
    position: 52,
  },
  {
    note: "Db5",
    key: "E",
    frequency: 554.365,
    type: "accidental",
    octave: 5,
    position: 53,
  },
  {
    note: "D5",
    key: "R",
    frequency: 587.33,
    type: "natural",
    octave: 5,
    position: 54,
  },
  {
    note: "Eb5",
    key: "T",
    frequency: 622.254,
    type: "accidental",
    octave: 5,
    position: 55,
  },
  {
    note: "E5",
    key: "Y",
    frequency: 659.255,
    type: "natural",
    octave: 5,
    position: 56,
  },
  {
    note: "F5",
    key: "U",
    frequency: 698.456,
    type: "natural",
    octave: 5,
    position: 57,
  },
  {
    note: "Gb5",
    key: "I",
    frequency: 739.989,
    type: "accidental",
    octave: 5,
    position: 58,
  },
  {
    note: "G5",
    key: "O",
    frequency: 783.991,
    type: "natural",
    octave: 5,
    position: 59,
  },
  {
    note: "Ab5",
    key: "P",
    frequency: 830.609,
    type: "accidental",
    octave: 5,
    position: 60,
  },
  {
    note: "A5",
    key: "[",
    frequency: 880.0,
    type: "natural",
    octave: 5,
    position: 61,
  },
  {
    note: "Bb5",
    key: "]",
    frequency: 932.328,
    type: "accidental",
    octave: 5,
    position: 62,
  },
  {
    note: "B5",
    key: "\\",
    frequency: 987.767,
    type: "natural",
    octave: 5,
    position: 63,
  },
  {
    note: "C6",
    key: "A",
    frequency: 1046.5,
    type: "natural",
    octave: 6,
    position: 64,
  },
  {
    note: "Db6",
    key: "S",
    frequency: 1108.73,
    type: "accidental",
    octave: 6,
    position: 65,
  },
  {
    note: "D6",
    key: "D",
    frequency: 1174.66,
    type: "natural",
    octave: 6,
    position: 66,
  },
  {
    note: "Eb6",
    key: "F",
    frequency: 1244.51,
    type: "accidental",
    octave: 6,
    position: 67,
  },
  {
    note: "E6",
    key: "G",
    frequency: 1318.51,
    type: "natural",
    octave: 6,
    position: 68,
  },
  {
    note: "F6",
    key: "H",
    frequency: 1396.91,
    type: "natural",
    octave: 6,
    position: 69,
  },
  {
    note: "Gb6",
    key: "J",
    frequency: 1479.98,
    type: "accidental",
    octave: 6,
    position: 70,
  },
  {
    note: "G6",
    key: "K",
    frequency: 1567.98,
    type: "natural",
    octave: 6,
    position: 71,
  },
  {
    note: "Ab6",
    key: "L",
    frequency: 1661.22,
    type: "accidental",
    octave: 6,
    position: 72,
  },
  {
    note: "A6",
    key: ";",
    frequency: 1760.0,
    type: "natural",
    octave: 6,
    position: 73,
  },
  {
    note: "Bb6",
    key: "'",
    frequency: 1864.66,
    type: "accidental",
    octave: 6,
    position: 74,
  },
  {
    note: "B6",
    key: "Z",
    frequency: 1975.53,
    type: "natural",
    octave: 6,
    position: 75,
  },
  {
    note: "C7",
    key: "X",
    frequency: 2093.01,
    type: "natural",
    octave: 7,
    position: 76,
  },
  {
    note: "Db7",
    key: "C",
    frequency: 2217.46,
    type: "accidental",
    octave: 7,
    position: 77,
  },
  {
    note: "D7",
    key: "V",
    frequency: 2349.32,
    type: "natural",
    octave: 7,
    position: 78,
  },
  {
    note: "Eb7",
    key: "B",
    frequency: 2489.02,
    type: "accidental",
    octave: 7,
    position: 79,
  },
  {
    note: "E7",
    key: "N",
    frequency: 2637.02,
    type: "natural",
    octave: 7,
    position: 80,
  },
  {
    note: "F7",
    key: "M",
    frequency: 2793.83,
    type: "natural",
    octave: 7,
    position: 81,
  },
  {
    note: "Gb7",
    key: ",",
    frequency: 2959.96,
    type: "accidental",
    octave: 7,
    position: 82,
  },
  {
    note: "G7",
    key: ".",
    frequency: 3135.96,
    type: "natural",
    octave: 7,
    position: 83,
  },
  {
    note: "Ab7",
    key: "/",
    frequency: 3322.44,
    type: "accidental",
    octave: 7,
    position: 84,
  },
  {
    note: "A7",
    key: "Q",
    frequency: 3520.0,
    type: "natural",
    octave: 7,
    position: 85,
  },
  {
    note: "Bb7",
    key: "W",
    frequency: 3729.31,
    type: "accidental",
    octave: 7,
    position: 86,
  },
  {
    note: "B7",
    key: "E",
    frequency: 3951.07,
    type: "natural",
    octave: 7,
    position: 87,
  },
  {
    note: "C8",
    key: "R",
    frequency: 4186.01,
    type: "natural",
    octave: 8,
    position: 88,
  },
];
